// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhlnsvrfatzxodhewsat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpobG5zdnJmYXR6eG9kaGV3c2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTQxMTYsImV4cCI6MjA2MjM5MDExNn0.IsqRzATPWLmd-_xVwMn3SjBLuZl17kd5NzROARnHyu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);